# Generated by Django 2.0.6 on 2018-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachingprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='coachingcontact',
            name='user',
        ),
        migrations.AddField(
            model_name='coachingcontact',
            name='username',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coachingcontact',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='CoachingProfile',
        ),
    ]
