# Generated by Django 2.0.6 on 2018-11-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181028_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('title', models.CharField(default='', max_length=500)),
                ('chapterid', models.CharField(default='', max_length=50)),
                ('chapter', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
