# Generated by Django 2.0.6 on 2018-11-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_coachingcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingcourse',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
