# Generated by Django 2.0.6 on 2018-11-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20181102_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingcourse',
            name='courseid',
            field=models.IntegerField(default=0),
        ),
    ]
