# Generated by Django 2.0.6 on 2018-11-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_coachingcourse_courseid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=500)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
