# Generated by Django 2.0.6 on 2018-11-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_courseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachingcontact',
            name='city',
            field=models.CharField(default='', max_length=500),
        ),
    ]
