# Generated by Django 2.0.6 on 2018-11-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_studentenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingAboutus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('aboutus', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CoachingAchievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=500)),
                ('achievements', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CoachingNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='CoachingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='created_at',
            field=models.DateTimeField(verbose_name=''),
        ),
    ]
