# Generated by Django 2.0.6 on 2018-11-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_coachingaboutus_aboutteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('image_txt_1', models.CharField(default='', max_length=100)),
                ('image_txt_2', models.CharField(default='', max_length=100)),
                ('courses', models.CharField(default='', max_length=100)),
                ('our_staff', models.CharField(default='', max_length=100)),
                ('latest_updates', models.CharField(default='', max_length=100)),
                ('placements', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('message', models.CharField(default='', max_length=5000)),
            ],
        ),
    ]
