# Generated by Django 2.0.6 on 2018-11-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_coachinghome_newcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcourses',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
