# Generated by Django 2.0.6 on 2018-09-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
