# Generated by Django 2.0.6 on 2018-09-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingprofile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
