# Generated by Django 2.0.6 on 2018-11-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20180922_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingprofile',
            name='url',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
